"""removed unnecessary classes

Revision ID: 93aad343a57b
Revises: 478827e6d735
Create Date: 2019-08-31 16:18:01.668685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aad343a57b'
down_revision = '478827e6d735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('net_owl__entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_owl__entity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('geoentity', sa.VARCHAR(length=10), nullable=True),
    sa.Column('geosubtype', sa.VARCHAR(length=25), nullable=True),
    sa.Column('geotype', sa.VARCHAR(length=25), nullable=True),
    sa.Column('entity_id', sa.VARCHAR(length=140), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.Column('norm', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ontology', sa.VARCHAR(length=125), nullable=True),
    sa.Column('pretext', sa.VARCHAR(length=255), nullable=True),
    sa.Column('value', sa.VARCHAR(length=255), nullable=True),
    sa.Column('posttext', sa.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('complete IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
