"""portal information

Revision ID: b265b05da33d
Revises: f695808d349e
Create Date: 2019-08-15 19:54:31.591855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b265b05da33d'
down_revision = 'f695808d349e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('portal_password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('portal_url', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('portal_username', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_portal_url'), 'user', ['portal_url'], unique=False)
    op.create_index(op.f('ix_user_portal_username'), 'user', ['portal_username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_portal_username'), table_name='user')
    op.drop_index(op.f('ix_user_portal_url'), table_name='user')
    op.drop_column('user', 'portal_username')
    op.drop_column('user', 'portal_url')
    op.drop_column('user', 'portal_password')
    # ### end Alembic commands ###
